module.exports = {
  users: require("./user.model"),
  roles: require("./role.model"),
  categories: require("./category.model"),
  recipes: require("./recipe.model"),
  fixed: require("./fixed.model"),
  product: require("./product.model"),
  qrbuildertable: require("./qrbuildertable.model"),
  languages: require("./language.model"),
  currency: require("./currency.model"),
  allOrder: require("./allOrder.model"),
  system: require("./generalSetting.model"),
  addons: require("./addons.model"),
  purchaseRequisition: require("./purchaseRequisition.model"),
};
